apiVersion: v1
kind: Service
metadata:
  name: podinfo-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
